[
 {port, 8080},
 {server_name, "barista"},
 {server_root, "/tmp"} ,
 {document_root, "./priv/html"},
 {bind_address, any},
 {modules, [
     mod_alias,
     mod_auth,
     mod_dir,
     mod_get,
     mod_auth,
     mod_log,
     mod_disk_log,
     mod_esi
 ]},
 {mime_types, [
     {"html", "text/html"},
     {"htm", "text/html"},
     {"css", "text/css"},
     {"js", "application/x-javascript"},
     {"json", "application/json"},
     {"png", "image/png"},
     {"jpg", "image/jpeg"}
 ]}
].
